<?php

namespace Database\Seeders;

use App\Models\Module;
use App\Models\SubscriptionPlan;
use Illuminate\Database\Seeder;

class ModulesAndPlansSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ========================================
        // MODULES DISPONIBLES
        // ========================================

        $modules = [
            // === MODULES CORE (inclus dans tous les plans) ===
            [
                'code' => 'core_boxes',
                'name' => 'Gestion des Boxes',
                'description' => 'Gestion complète des boxes, plan visuel, statuts et disponibilités',
                'icon' => 'cube',
                'color' => 'blue',
                'category' => 'core',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'is_core' => true,
                'features' => [
                    'Plan visuel interactif',
                    'Gestion des bâtiments/étages',
                    'Historique des boxes',
                    'Import/Export données',
                ],
                'routes' => ['tenant.boxes.*', 'tenant.plan.*', 'tenant.sites.*'],
                'sort_order' => 1,
            ],
            [
                'code' => 'core_customers',
                'name' => 'Gestion Clients',
                'description' => 'Fichier clients complet avec historique et documents',
                'icon' => 'users',
                'color' => 'green',
                'category' => 'core',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'is_core' => true,
                'features' => [
                    'Fiche client détaillée',
                    'Historique complet',
                    'Documents associés',
                    'Recherche avancée',
                ],
                'routes' => ['tenant.customers.*'],
                'sort_order' => 2,
            ],
            [
                'code' => 'core_contracts',
                'name' => 'Gestion Contrats',
                'description' => 'Création, signature électronique et suivi des contrats',
                'icon' => 'document-text',
                'color' => 'indigo',
                'category' => 'core',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'is_core' => true,
                'features' => [
                    'Création de contrats',
                    'Modèles personnalisables',
                    'Suivi des échéances',
                    'Renouvellement automatique',
                ],
                'routes' => ['tenant.contracts.*'],
                'sort_order' => 3,
            ],
            [
                'code' => 'core_invoicing',
                'name' => 'Facturation',
                'description' => 'Facturation manuelle et automatique, export comptable',
                'icon' => 'receipt-percent',
                'color' => 'emerald',
                'category' => 'core',
                'monthly_price' => 0,
                'yearly_price' => 0,
                'is_core' => true,
                'features' => [
                    'Factures automatiques',
                    'Factures manuelles',
                    'Export PDF',
                    'Historique paiements',
                ],
                'routes' => ['tenant.invoices.*', 'tenant.bulk-invoicing.*'],
                'sort_order' => 4,
            ],

            // === MODULES MARKETING ===
            [
                'code' => 'crm',
                'name' => 'CRM & Leads',
                'description' => 'Gestion des prospects, pipeline commercial et conversion',
                'icon' => 'user-group',
                'color' => 'purple',
                'category' => 'marketing',
                'monthly_price' => 29,
                'yearly_price' => 290,
                'is_core' => false,
                'features' => [
                    'Pipeline de vente',
                    'Suivi des prospects',
                    'Scoring automatique',
                    'Historique des interactions',
                    'Rapports de conversion',
                ],
                'routes' => ['tenant.crm.*', 'tenant.prospects.*'],
                'sort_order' => 10,
            ],
            [
                'code' => 'sms_campaigns',
                'name' => 'Campagnes SMS',
                'description' => 'Envoi de SMS marketing et transactionnels en masse',
                'icon' => 'device-phone-mobile',
                'color' => 'pink',
                'category' => 'marketing',
                'monthly_price' => 19,
                'yearly_price' => 190,
                'is_core' => false,
                'features' => [
                    'Campagnes SMS en masse',
                    'Segmentation clients',
                    'Templates SMS',
                    'Statistiques d\'envoi',
                    'Programmation différée',
                ],
                'routes' => ['tenant.crm.campaigns.*'],
                'dependencies' => ['crm'],
                'sort_order' => 11,
            ],
            [
                'code' => 'email_marketing',
                'name' => 'Email Marketing',
                'description' => 'Campagnes email professionnelles avec templates',
                'icon' => 'envelope',
                'color' => 'orange',
                'category' => 'marketing',
                'monthly_price' => 25,
                'yearly_price' => 250,
                'is_core' => false,
                'features' => [
                    'Templates email personnalisables',
                    'Campagnes automatisées',
                    'Tracking des ouvertures',
                    'A/B Testing',
                    'Segmentation avancée',
                ],
                'routes' => ['tenant.email-campaigns.*'],
                'sort_order' => 12,
            ],

            // === MODULES OPERATIONS ===
            [
                'code' => 'sepa',
                'name' => 'Prélèvements SEPA',
                'description' => 'Gestion des mandats et prélèvements automatiques SEPA',
                'icon' => 'credit-card',
                'color' => 'blue',
                'category' => 'operations',
                'monthly_price' => 39,
                'yearly_price' => 390,
                'is_core' => false,
                'features' => [
                    'Mandats SEPA B2B et B2C',
                    'Prélèvements automatiques',
                    'Gestion des rejets',
                    'Export bancaire XML',
                    'Signature électronique des mandats',
                ],
                'routes' => ['tenant.sepa-mandates.*'],
                'sort_order' => 20,
            ],
            [
                'code' => 'signatures',
                'name' => 'Signature Électronique',
                'description' => 'Signature électronique des contrats et documents',
                'icon' => 'pencil-square',
                'color' => 'violet',
                'category' => 'operations',
                'monthly_price' => 29,
                'yearly_price' => 290,
                'is_core' => false,
                'features' => [
                    'Signature en ligne',
                    'Validité légale',
                    'Horodatage',
                    'Archivage sécurisé',
                    'Multi-signataires',
                ],
                'routes' => ['tenant.signatures.*'],
                'sort_order' => 21,
            ],
            [
                'code' => 'reminders',
                'name' => 'Relances Impayés',
                'description' => 'Automatisation des relances et gestion des impayés',
                'icon' => 'bell-alert',
                'color' => 'red',
                'category' => 'operations',
                'monthly_price' => 19,
                'yearly_price' => 190,
                'is_core' => false,
                'features' => [
                    'Relances automatiques',
                    'Scénarios personnalisables',
                    'Email + SMS',
                    'Historique des relances',
                    'Tableau de bord impayés',
                ],
                'routes' => ['tenant.reminders.*', 'tenant.overdue.*'],
                'sort_order' => 22,
            ],
            [
                'code' => 'maintenance',
                'name' => 'Maintenance & SAV',
                'description' => 'Gestion des interventions et tickets de maintenance',
                'icon' => 'wrench-screwdriver',
                'color' => 'gray',
                'category' => 'operations',
                'monthly_price' => 25,
                'yearly_price' => 250,
                'is_core' => false,
                'features' => [
                    'Tickets de maintenance',
                    'Planning techniciens',
                    'Historique interventions',
                    'Pièces jointes',
                    'Coûts de maintenance',
                ],
                'routes' => ['tenant.maintenance.*'],
                'sort_order' => 23,
            ],
            [
                'code' => 'access_control',
                'name' => 'Contrôle d\'Accès',
                'description' => 'Intégration avec les systèmes de contrôle d\'accès',
                'icon' => 'lock-closed',
                'color' => 'slate',
                'category' => 'operations',
                'monthly_price' => 49,
                'yearly_price' => 490,
                'is_core' => false,
                'features' => [
                    'Gestion des badges',
                    'Codes d\'accès dynamiques',
                    'Logs d\'accès',
                    'Intégration serrures connectées',
                    'Accès temporaires',
                ],
                'routes' => ['tenant.access-control.*'],
                'sort_order' => 24,
            ],

            // === MODULES INTEGRATIONS ===
            [
                'code' => 'api',
                'name' => 'API & Webhooks',
                'description' => 'API REST complète et webhooks pour intégrations tierces',
                'icon' => 'code-bracket',
                'color' => 'cyan',
                'category' => 'integrations',
                'monthly_price' => 49,
                'yearly_price' => 490,
                'is_core' => false,
                'features' => [
                    'API REST documentée',
                    'Webhooks temps réel',
                    'Clés API multiples',
                    'Rate limiting configurable',
                    'Logs des appels API',
                ],
                'routes' => ['tenant.api.*', 'api.*'],
                'sort_order' => 30,
            ],
            [
                'code' => 'booking_widget',
                'name' => 'Widget de Réservation',
                'description' => 'Widget intégrable sur votre site web pour réservations en ligne',
                'icon' => 'globe-alt',
                'color' => 'teal',
                'category' => 'integrations',
                'monthly_price' => 39,
                'yearly_price' => 390,
                'is_core' => false,
                'features' => [
                    'Widget responsive',
                    'Personnalisation couleurs',
                    'Paiement en ligne',
                    'Réservation temps réel',
                    'Confirmation automatique',
                ],
                'routes' => ['public.booking.*', 'tenant.booking-widget.*'],
                'sort_order' => 31,
            ],
            [
                'code' => 'accounting',
                'name' => 'Intégration Comptable',
                'description' => 'Export FEC et intégration avec logiciels comptables',
                'icon' => 'building-library',
                'color' => 'amber',
                'category' => 'integrations',
                'monthly_price' => 35,
                'yearly_price' => 350,
                'is_core' => false,
                'features' => [
                    'Export FEC',
                    'Plan comptable personnalisable',
                    'Intégration Sage, Cegid...',
                    'Lettrage automatique',
                    'Journal des écritures',
                ],
                'routes' => ['tenant.fec.*', 'tenant.accounting.*'],
                'sort_order' => 32,
            ],
            [
                'code' => 'payment_gateway',
                'name' => 'Paiement en Ligne',
                'description' => 'Stripe, PayPal et autres moyens de paiement en ligne',
                'icon' => 'banknotes',
                'color' => 'green',
                'category' => 'integrations',
                'monthly_price' => 29,
                'yearly_price' => 290,
                'is_core' => false,
                'features' => [
                    'Stripe integration',
                    'PayPal',
                    'Paiement 3x/4x',
                    'Remboursements automatiques',
                    'Réconciliation',
                ],
                'routes' => ['tenant.payments.*', 'tenant.payment-gateway.*'],
                'sort_order' => 33,
            ],

            // === MODULES PREMIUM/ANALYTICS ===
            [
                'code' => 'analytics_advanced',
                'name' => 'Analytics Avancés',
                'description' => 'Tableaux de bord avancés et prévisions',
                'icon' => 'chart-bar-square',
                'color' => 'indigo',
                'category' => 'analytics',
                'monthly_price' => 49,
                'yearly_price' => 490,
                'is_core' => false,
                'features' => [
                    'Dashboards personnalisables',
                    'Prévisions IA',
                    'Analyses comparatives',
                    'Export rapports',
                    'Alertes automatiques',
                ],
                'routes' => ['tenant.analytics.*'],
                'sort_order' => 40,
            ],
            [
                'code' => 'ai_advisor',
                'name' => 'Conseiller IA',
                'description' => 'Recommandations intelligentes pour optimiser vos revenus',
                'icon' => 'light-bulb',
                'color' => 'yellow',
                'category' => 'analytics',
                'monthly_price' => 59,
                'yearly_price' => 590,
                'is_core' => false,
                'features' => [
                    'Conseils personnalisés',
                    'Détection des opportunités',
                    'Optimisation des prix',
                    'Prédiction du churn',
                    'Score de santé business',
                ],
                'routes' => ['tenant.ai-advisor.*'],
                'sort_order' => 41,
            ],
            [
                'code' => 'dynamic_pricing',
                'name' => 'Pricing Dynamique',
                'description' => 'Optimisation automatique des prix selon la demande',
                'icon' => 'arrow-trending-up',
                'color' => 'rose',
                'category' => 'premium',
                'monthly_price' => 69,
                'yearly_price' => 690,
                'is_core' => false,
                'features' => [
                    'Prix selon occupation',
                    'Saisonnalité',
                    'Promotions automatiques',
                    'Tests A/B de prix',
                    'Historique des variations',
                ],
                'routes' => ['tenant.pricing.*'],
                'sort_order' => 42,
            ],
            [
                'code' => 'multi_sites',
                'name' => 'Multi-Sites',
                'description' => 'Gestion de plusieurs sites depuis un seul compte',
                'icon' => 'building-office-2',
                'color' => 'sky',
                'category' => 'premium',
                'monthly_price' => 99,
                'yearly_price' => 990,
                'is_core' => false,
                'features' => [
                    'Nombre de sites illimité',
                    'Vue consolidée',
                    'Rapports multi-sites',
                    'Utilisateurs par site',
                    'Facturation centralisée',
                ],
                'routes' => ['tenant.sites.*'],
                'sort_order' => 43,
            ],
            [
                'code' => 'white_label',
                'name' => 'White Label',
                'description' => 'Personnalisation complète avec votre marque',
                'icon' => 'paint-brush',
                'color' => 'fuchsia',
                'category' => 'premium',
                'monthly_price' => 149,
                'yearly_price' => 1490,
                'is_core' => false,
                'features' => [
                    'Domaine personnalisé',
                    'Logo et couleurs',
                    'Emails depuis votre domaine',
                    'Suppression mentions Boxibox',
                    'Support prioritaire',
                ],
                'routes' => ['tenant.branding.*'],
                'sort_order' => 44,
            ],
        ];

        foreach ($modules as $moduleData) {
            Module::updateOrCreate(
                ['code' => $moduleData['code']],
                $moduleData
            );
        }

        // ========================================
        // PLANS D'ABONNEMENT
        // ========================================

        $coreModuleIds = Module::where('is_core', true)->pluck('id')->toArray();

        $plans = [
            [
                'code' => 'starter',
                'name' => 'Starter',
                'description' => 'Pour les petits sites de self-stockage débutants',
                'badge_color' => 'gray',
                'monthly_price' => 49,
                'yearly_price' => 470,
                'yearly_discount' => 20,
                'max_sites' => 1,
                'max_boxes' => 50,
                'max_users' => 2,
                'max_customers' => 100,
                'includes_support' => true,
                'support_level' => 'email',
                'included_modules' => $coreModuleIds,
                'features' => [
                    'Gestion des boxes',
                    'Clients & Contrats',
                    'Facturation de base',
                    'Support par email',
                ],
                'is_popular' => false,
                'sort_order' => 1,
            ],
            [
                'code' => 'professional',
                'name' => 'Professional',
                'description' => 'Pour les sites en croissance avec plus de fonctionnalités',
                'badge_color' => 'blue',
                'monthly_price' => 99,
                'yearly_price' => 950,
                'yearly_discount' => 20,
                'max_sites' => 1,
                'max_boxes' => 200,
                'max_users' => 5,
                'max_customers' => 500,
                'includes_support' => true,
                'support_level' => 'priority',
                'included_modules' => array_merge(
                    $coreModuleIds,
                    Module::whereIn('code', ['crm', 'sepa', 'signatures', 'reminders'])->pluck('id')->toArray()
                ),
                'features' => [
                    'Tout du Starter',
                    'CRM & Leads',
                    'Prélèvements SEPA',
                    'Signature électronique',
                    'Relances impayés',
                    'Support prioritaire',
                ],
                'is_popular' => true,
                'sort_order' => 2,
            ],
            [
                'code' => 'business',
                'name' => 'Business',
                'description' => 'Pour les entreprises avec besoins avancés',
                'badge_color' => 'purple',
                'monthly_price' => 199,
                'yearly_price' => 1910,
                'yearly_discount' => 20,
                'max_sites' => 3,
                'max_boxes' => 500,
                'max_users' => 10,
                'max_customers' => null,
                'includes_support' => true,
                'support_level' => 'priority',
                'included_modules' => array_merge(
                    $coreModuleIds,
                    Module::whereIn('code', [
                        'crm', 'sms_campaigns', 'email_marketing',
                        'sepa', 'signatures', 'reminders', 'maintenance',
                        'api', 'booking_widget', 'accounting', 'payment_gateway',
                        'analytics_advanced'
                    ])->pluck('id')->toArray()
                ),
                'features' => [
                    'Tout du Professional',
                    'Campagnes SMS & Email',
                    'Maintenance & SAV',
                    'API & Webhooks',
                    'Widget de réservation',
                    'Intégration comptable',
                    'Analytics avancés',
                    'Jusqu\'à 3 sites',
                ],
                'is_popular' => false,
                'sort_order' => 3,
            ],
            [
                'code' => 'enterprise',
                'name' => 'Enterprise',
                'description' => 'Solution complète pour les grands réseaux de self-stockage',
                'badge_color' => 'amber',
                'monthly_price' => 399,
                'yearly_price' => 3830,
                'yearly_discount' => 20,
                'max_sites' => null,
                'max_boxes' => null,
                'max_users' => null,
                'max_customers' => null,
                'includes_support' => true,
                'support_level' => 'dedicated',
                'included_modules' => Module::pluck('id')->toArray(), // Tous les modules
                'features' => [
                    'Tous les modules inclus',
                    'Sites illimités',
                    'Boxes illimités',
                    'Utilisateurs illimités',
                    'Conseiller IA',
                    'Pricing dynamique',
                    'White Label',
                    'Support dédié',
                    'Formation incluse',
                    'SLA garanti 99.9%',
                ],
                'is_popular' => false,
                'sort_order' => 4,
            ],
        ];

        foreach ($plans as $planData) {
            SubscriptionPlan::updateOrCreate(
                ['code' => $planData['code']],
                $planData
            );
        }

        $this->command->info('Modules et plans créés avec succès!');
    }
}
